### ISSUE TITLE
How to train it on ImageNet?

### ISSUE THREAD

**Issue by FouriYe** [LanchJL/IAB-GZSL#1]
A good work. I want to reproduce it on ImageNet. How can I train it on ImageNet?

**Comment by LanchJL** [comment]
Hi, thanks for your interest in our work.

Due to significant modifications involved in using CLIP as a backbone on ImageNet by the IAB, we have not incorporated it into this code. Our implementation of ImageNet is based on the CLIP baseline from [HGR-Net](https://github.com/WilliamYi96/HGR-Net). To train the model, the NAA (in model.py) should be connected to the text encoder, and the VARS (in model.py) should be connected to the patch token from the image encoder.
